import { nanoid } from "nanoid";
export const movies = [
  {
    id: nanoid(),
    img: "/images/wicked.jpg",
    rating: 6.9,
    name: "Wicked",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/alien.jpg",
    rating: 8.6,
    name: "Alien",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/dearsanta.jpg",
    rating: 8.8,
    name: "Dear Santa",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/dragon.jpg",
    rating: 8.8,
    name: "Dragon 3D",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/fromtheashes.jpg",
    rating: 8.8,
    name: "From The Ashes",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/wicked.jpg",
    rating: 6.9,
    name: "Wicked",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/alien.jpg",
    rating: 8.6,
    name: "Alien",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/dearsanta.jpg",
    rating: 8.8,
    name: "Dear Santa",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/dragon.jpg",
    rating: 8.8,
    name: "Dragon 3D",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/fromtheashes.jpg",
    rating: 8.8,
    name: "From The Ashes",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/fromtheashes.jpg",
    rating: 8.8,
    name: "From The Ashes",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/wicked.jpg",
    rating: 6.9,
    name: "Wicked",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/alien.jpg",
    rating: 8.6,
    name: "Alien",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/dearsanta.jpg",
    rating: 8.8,
    name: "Dear Santa",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/dragon.jpg",
    rating: 8.8,
    name: "Dragon 3D",
    description: "Movie description..",
  },
  {
    id: nanoid(),
    img: "/images/fromtheashes.jpg",
    rating: 8.8,
    name: "From The Ashes",
    description: "Movie description..",
  },
];
